GET http://localhost:5049/profile
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJFbWFpbCI6ImFAZ21haWwuY29tIiwiUGFzc3dvcmQiOiIkMmIkMTAkbVh4ZGxGTUc1TDNLT2F0dkdHY2JTLjlLRDBqb2d1QzVGa2VWUE5uSmFDYzd6M0VIdnRIcGkiLCJpYXQiOjE2MzQzMTcwODN9.Ma-ETt8opgg46J1otP0GQsQg3fv9446WsS63C7wqI2g